apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nsi-pce.fullname" . }}
  labels:
    {{- include "nsi-pce.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Chart.Name }}
  selector:
    matchLabels:
      {{- include "nsi-pce.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nsi-pce.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nsi-pce.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: wait-for-dds
        image: curlimages/curl:latest
        command: ["sh", "-c",
          {{ printf "until [ $(curl -sw '%%{http_code}' http://%s-%s.%s.svc.cluster.local:80/dds/portal -o /dev/null) -eq 200 ]; do echo `date` sleeping 2 seconds ...; sleep 2; done" .Release.Name .Chart.Name .Release.Namespace | quote }}
        ]
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["java"]
          args:
            - "-Xmx10000m"
            - "-Djava.net.preferIPv4Stack=true"
            - "-Dcom.sun.xml.bind.v2.runtime.JAXBContextImpl.fastBoot=true"
            - "-Djavax.net.ssl.trustStoreType=jks"
            - "-Djavax.net.ssl.keyStoreType=jks"
            - "-Djavax.net.ssl.trustStorePassword=secret"
            - "-Djavax.net.ssl.keyStorePassword=secret"
            - {{ printf "-Djavax.net.ssl.trustStore=%s/nsi-pce-truststore.jks" .Values.config.mountPath | quote }}
            - {{ printf "-Djavax.net.ssl.keyStore=%s/nsi-pce-keystore.jks" .Values.config.mountPath | quote }}
            - {{ printf "-Djava.util.logging.config.file=%s/logging.properties" .Values.config.mountPath | quote }}
            - {{ printf "-Dlog4j.configuration=%s/log4j.xml" .Values.config.mountPath | quote }}
            - {{ printf "-Dapp.home=%s" .Values.image.home | quote }}
            - {{ printf "-Dbasedir=%s" .Values.image.home | quote }}
            - "-jar"
            - {{ printf "%s/pce.jar" .Values.image.home | quote }}
            - {{ printf "-topologyConfigFile=%s/topology-dds.xml" .Values.config.mountPath | quote }}
          volumeMounts:
            - name: {{ .Values.config.name }}
              mountPath: {{ .Values.config.mountPath }}
              readOnly: true
          ports:
            - name: internal
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              scheme: {{ .Values.livenessProbe.scheme }}
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.service.containerPort }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              scheme: {{ .Values.startupProbe.scheme }}
              path: {{ .Values.startupProbe.path }}
              port: {{ .Values.service.containerPort }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ .Values.config.name }}
          configMap:
            name: {{ .Values.config.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
